name: travel_planner
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  animate_do: ^3.1.2
  chatview: ^1.3.1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  lottie: ^2.6.0
  google_fonts: ^6.1.0
  chatview: ^1.3.1
  objectbox: ^2.3.0
  objectbox_flutter_libs: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1
  sqflite: ^2.3.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  objectbox_generator: ^2.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/font/euclid/

  fonts:
    - family: Euclid
      fonts:
        - asset: assets/font/euclid/Euclid-Circular-A-300.ttf
          weight: 300
        - asset: assets/font/euclid/Euclid-Circular-A-400.ttf
          weight: 400
        - asset: assets/font/euclid/Euclid-Circular-A-500.ttf
          weight: 500
        - asset: assets/font/euclid/Euclid-Circular-A-600.ttf
          weight: 600
        - asset: assets/font/euclid/Euclid-Circular-A-700.ttf
          weight: 700
