// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'data/model/conversation.dart';
import 'data/model/message.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(3, 7648255137539140142),
      name: 'ObjConversation',
      lastPropertyId: const IdUid(2, 1297011259019299411),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 6007608426916279166),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 1297011259019299411),
            name: 'title',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[
        ModelBacklink(
            name: 'messages', srcEntity: 'ObjMessage', srcField: 'conversation')
      ]),
  ModelEntity(
      id: const IdUid(4, 824177915932421437),
      name: 'ObjMessage',
      lastPropertyId: const IdUid(5, 4762973036752310139),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 4526988293094932573),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 2352766510614573616),
            name: 'text',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 7027310359784485672),
            name: 'createdAt',
            type: 10,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 5182205242350712346),
            name: 'sentBy',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 4762973036752310139),
            name: 'conversationId',
            type: 11,
            flags: 520,
            indexId: const IdUid(2, 7588266359802050252),
            relationTarget: 'ObjConversation')
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Shortcut for [Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [Store.new] for an explanation of all parameters.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// Returns the ObjectBox model definition for this project for use with
/// [Store.new].
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(4, 824177915932421437),
      lastIndexId: const IdUid(2, 7588266359802050252),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [6715182166202861895, 548786419347908769],
      retiredIndexUids: const [],
      retiredPropertyUids: const [
        7444668573304446545,
        2935179644779578314,
        4464755024944176890,
        2228122125001173981,
        8322707654890505512,
        1988776387876255736,
        1206206859841136853
      ],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    ObjConversation: EntityDefinition<ObjConversation>(
        model: _entities[0],
        toOneRelations: (ObjConversation object) => [],
        toManyRelations: (ObjConversation object) => {
              RelInfo<ObjMessage>.toOneBacklink(5, object.id,
                      (ObjMessage srcObject) => srcObject.conversation):
                  object.messages
            },
        getId: (ObjConversation object) => object.id,
        setId: (ObjConversation object, int id) {
          object.id = id;
        },
        objectToFB: (ObjConversation object, fb.Builder fbb) {
          final titleOffset =
              object.title == null ? null : fbb.writeString(object.title!);
          fbb.startTable(3);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, titleOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final titleParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 6);
          final object = ObjConversation(id: idParam, title: titleParam);
          InternalToManyAccess.setRelInfo<ObjConversation>(
              object.messages,
              store,
              RelInfo<ObjMessage>.toOneBacklink(5, object.id,
                  (ObjMessage srcObject) => srcObject.conversation));
          return object;
        }),
    ObjMessage: EntityDefinition<ObjMessage>(
        model: _entities[1],
        toOneRelations: (ObjMessage object) => [object.conversation],
        toManyRelations: (ObjMessage object) => {},
        getId: (ObjMessage object) => object.id,
        setId: (ObjMessage object, int id) {
          object.id = id;
        },
        objectToFB: (ObjMessage object, fb.Builder fbb) {
          final textOffset = fbb.writeString(object.text);
          final sentByOffset = fbb.writeString(object.sentBy);
          fbb.startTable(6);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, textOffset);
          fbb.addInt64(2, object.createdAt.millisecondsSinceEpoch);
          fbb.addOffset(3, sentByOffset);
          fbb.addInt64(4, object.conversation.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final textParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0));
          final sentByParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final object = ObjMessage(
              text: textParam, createdAt: createdAtParam, sentBy: sentByParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          object.conversation.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0);
          object.conversation.attach(store);
          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [ObjConversation] entity fields to define ObjectBox queries.
class ObjConversation_ {
  /// see [ObjConversation.id]
  static final id =
      QueryIntegerProperty<ObjConversation>(_entities[0].properties[0]);

  /// see [ObjConversation.title]
  static final title =
      QueryStringProperty<ObjConversation>(_entities[0].properties[1]);
}

/// [ObjMessage] entity fields to define ObjectBox queries.
class ObjMessage_ {
  /// see [ObjMessage.id]
  static final id =
      QueryIntegerProperty<ObjMessage>(_entities[1].properties[0]);

  /// see [ObjMessage.text]
  static final text =
      QueryStringProperty<ObjMessage>(_entities[1].properties[1]);

  /// see [ObjMessage.createdAt]
  static final createdAt =
      QueryIntegerProperty<ObjMessage>(_entities[1].properties[2]);

  /// see [ObjMessage.sentBy]
  static final sentBy =
      QueryStringProperty<ObjMessage>(_entities[1].properties[3]);

  /// see [ObjMessage.conversation]
  static final conversation = QueryRelationToOne<ObjMessage, ObjConversation>(
      _entities[1].properties[4]);
}
